
module.exports = {
    MESSAGE: {
        welcome: 'Hi, welcome to Pluto Mutual Fund Services. What service would you like to use?\n <b>Below are some Quick Suggestions:</b>',
        reply_option_msg: 'What would you like to do?',
        fallback_welcome: 'Hi, welcome to Pluto Mutual Fund Services. Please type your request.',
        invalid_input: 'Sorry, I didn’t understand that. Can you try again?',
        explore_funds_greeting: 'Kindly select one of the below categories:',
        select_portfolio_msg: 'Kindly select one of your portfolios:',
        mobile_options: ["Enter Registered Number Again", "Main Menu"],
        enter_mobile: 'Please enter your 10-digit mobile number to proceed with %s',
        no_category: 'No fund categories found. Please try again later.',
        no_portfolio_invest_options: ["Invest More", "Enter Registered Number Again", "Main Menu"],
        no_portfolio_found_msg: 'No Portfolio found associted to this number',
        no_record_msg: 'No record found for this number. Please register or try again later.',
        no_fund: 'Sorry, I couldn\'t find that fund.',
        no_fund_selection: 'No fund selected. Please choose a fund first.',
        no_transaction: 'No transactions found.',
        no_chart: 'Chart not available for this fund.',
        no_portfolio_found: 'No portfolios found for your number.\nPlease try again with a registered number or go back to the main menu.',
        something_wrong: 'Something went wrong. Please start again from the main menu use /start',
        enter_number: 'Please enter a valid 10-digit mobile number.',
        select_year_type: ' Kindly provide a time period to view your transaction history:',
        thankyou_msg: 'Thank you for using our services. Have a great day!',
        fund_category_continue: 'Kindly select a fund category to continue:',
        invest_more_msg: 'Great! Let’s help you invest more.',
        tryAgain_investment: 'Try again : Investment amount',
        select_category: 'Here are the funds under <b>%s</b> category. Please select one:',
        date_format_error:'I couldn\'t understand that date format. Please try again with a clearer date or range.',
        select_range: 'Please enter a valid date or date range (e.g., April 2023, 10 April 2024 to 25 April 2024).',
        select_investment_amount: 'Please enter or select an investment amount (less than ₹50,000):',
        investment_amount_options: ['1000', '2000', '5000', '10000'],
    },
    INTENT_NAME: {
        welcome: 'Default Welcome Intent',
        explore_funds: 'Explore Funds',
        fund_category_selection: 'Fund Category Selection',
        fundSelection: 'Fund Detail Selection',
        capture_contact: "Capture Contact",
        re_eneter_contact: 'ReEnter Contact',
        portfolio_valuation: "Portfolio Valuation",
        transaction_history: "Transaction History",
        portfolio_selection: "Select Portfolio",
        capture_txn_date: 'Capture Transaction Date',
        invest_now: 'Invest Now',
        user_invest_more: 'User Wants to Invest More',
        capture_investment_amount: 'Capture Investment Amount',
        user_exit: 'User Wants to Exit',
        download_txn_intent: 'Download Transaction Excel',
        view_chart: 'View Chart'
    }
}